// API Client - provides a mockable API client for the Fixed Deposit journey

export { createApiClient, apiClient, mockApiClient } from './api-client.js';
export { ApiClientProvider, useApiClient, useApiClientOptional, useApiClientWithFallback } from './api-client-context.js';
export type {
  ApiClient,
  ApiClientConfig,
  ApiResponse,
  ValidationError,
  Term,
  TermsResponse,
  AuthorizeRequest,
  AuthorizeResponse,
  TokenRequest,
  TokenResponse,
  JourneyConfig,
  JourneyConfigResponse,
  DepositRequest,
  BankRequest,
  SuccessResponse,
  ErrorResponse,
  FDCalculatorRequest,
  FDCalculatorResponse,
  SubmitResponse,
  BranchesRequest,
  BranchesResponse,
  Branch,
  SessionResponse,
  IFSCLookupResponse,
  AccountVerifyRequest,
  AccountVerifyResponse,
  CustomerAccountsRequest,
  CustomerAccount,
  TranslationsResponse,
  NomineeDetails,
  NomineeResponse,
} from './types.js';
