/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { PaymentInitiationArgs } from '../models/PaymentInitiationArgs.js';
import type { PaymentStatusArgs } from '../models/PaymentStatusArgs.js';
import type { PaymentStatusResult } from '../models/PaymentStatusResult.js';
import type { CancelablePromise } from '../core/CancelablePromise.js';
import { OpenAPI } from '../core/OpenAPI.js';
import { request as __request } from '../core/request.js';
export class PaymentService {
    /**
     * Receive payment callback from CCAvenue
     * Operation to receive callback from CCAvenue on the completion of payment capture.
     * @param requestBody
     * @param traceparent W3C Trace Context traceparent header for distributed tracing. See: https://www.w3.org/TR/trace-context/#traceparent-header
     * @returns any HTML response
     * @throws ApiError
     */
    public static postCcavenueCallback(
        requestBody: string,
        traceparent?: string,
    ): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/ccavenue/callback',
            headers: {
                'traceparent': traceparent,
            },
            body: requestBody,
            mediaType: 'text/plain',
            errors: {
                400: `Bad Request`,
                401: `Unauthorized`,
                403: `Forbidden`,
                404: `Not Found`,
                424: `Failed Dependency`,
                500: `Internal Server Error`,
            },
        });
    }
    /**
     * Initiate payment
     * Operation to initiate a payment for a customer. Returns a JSON object with payment link details or HTML content for redirection.
     * @param requestBody
     * @param traceparent W3C Trace Context traceparent header for distributed tracing. See: https://www.w3.org/TR/trace-context/#traceparent-header
     * @param idempotencyKey Idempotency key to ensure safe retries and check status of previous requests. Use a unique identifier (UUID recommended). If this key was used in a previous request, the API will return the current status of that original operation instead of creating a duplicate. This allows both safe retries and status inquiries using the same mechanism. See: https://datatracker.ietf.org/doc/html/draft-ietf-httpapi-idempotency-key-header-06
     * @returns any Accepted
     * @throws ApiError
     */
    public static postPayments(
        requestBody: PaymentInitiationArgs,
        traceparent?: string,
        idempotencyKey?: string,
    ): CancelablePromise<{
        /**
         * Unique reference generated by Stitch for the payment transaction
         */
        paymentTxnId?: string;
        /**
         * URL to redirect the user for payment
         */
        paymentLink?: {
            /**
             * URL to redirect the user for payment
             */
            url?: string;
            /**
             * HTTP method to be used to post to the URL
             */
            method?: string;
            /**
             * Additional parameters to include in the payment request
             */
            parameters?: Record<string, string>;
        };
    }> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/payments',
            headers: {
                'traceparent': traceparent,
                'Idempotency-Key': idempotencyKey,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad Request`,
                401: `Unauthorized`,
                403: `Forbidden`,
                404: `Not found`,
                409: `Conflict`,
                424: `Failed Dependency`,
                500: `Internal Server Error`,
            },
        });
    }
    /**
     * Fetch payment status
     * Operation to fetch the status of a payment for a customer. Returns a JSON object with the payment status.
     * @param requestBody
     * @param traceparent W3C Trace Context traceparent header for distributed tracing. See: https://www.w3.org/TR/trace-context/#traceparent-header
     * @returns PaymentStatusResult OK
     * @throws ApiError
     */
    public static postPaymentsStatus(
        requestBody: PaymentStatusArgs,
        traceparent?: string,
    ): CancelablePromise<PaymentStatusResult> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/payments/status',
            headers: {
                'traceparent': traceparent,
            },
            body: requestBody,
            mediaType: 'application/json',
            errors: {
                400: `Bad Request`,
                401: `Unauthorized`,
                403: `Forbidden`,
                404: `Not Found`,
                424: `Failed Dependency`,
                500: `Internal Server Error`,
            },
        });
    }
}
