/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
/**
 * Result data returned after successful payment initiation
 */
export type PaymentInitiationResult = {
    /**
     * Unique reference generated by Stitch for the payment transaction
     */
    paymentTxnId?: string;
    /**
     * URL to redirect the user for payment
     */
    paymentLink?: {
        /**
         * URL to redirect the user for payment
         */
        url?: string;
        /**
         * HTTP method to be used to post to the URL
         */
        method?: string;
        /**
         * Additional parameters to include in the payment request
         */
        parameters?: Record<string, string>;
    };
};

