/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { PaymentTransactionStatus } from './PaymentTransactionStatus.js';
/**
 * Status of the payment transaction
 */
export type PaymentStatusResult = {
    /**
     * Unique reference generated by Stitch for the payment transaction
     */
    paymentTxnId?: string;
    /**
     * Unique reference generated by Payment gateway for the payment transaction
     */
    status?: PaymentTransactionStatus;
    /**
     * Unique reference generated by client reference number
     */
    clientReferenceNumber?: string;
};

